{block #content}

<div id="posts">
	{if !empty($posts)}

		{foreach $posts as $post}
			<div class="post">
				<h2 class="entry-title"><a href="{plink Default:post 'slug'=>$post->slug}">{$post->headline}</a></h2>
				<p class="entry-date">{$post->created->format('M j, Y')}</p>
				<p class="comments-link"><a href="{plink Default:post 'slug'=>$post->slug}#comments" title="comments">{$post->commentsCount}</a></p>

				<div class="entry-content">
					{!$post->text|perex}
				</div><!-- .entry-content -->

				<p class="tag-links">
					<span>tags: </span>
					{foreach $post->tags as $tag}
						<a href="{plink Default:tag 'tag'=>$tag->name}">{$tag->name}</a>
						{if !$iterator->isLast()}|{/if}
					{/foreach}
				</p>
			</div><!-- .post -->
		{/foreach}

	{else}

		<p>No Posts!</p>

	{/if}
</div><!-- #posts -->
