{block #javascripts}
	<script src="{$basePath}/js/jquery.nette.js"></script>
	<script src="{$basePath}/js/jquery.ajaxform.js"></script>
	<script src="{$basePath}/js/views/post.js"></script>
{/block}


{block #content}

<div id="posts">

	<div class="post single">
		<h2 class="entry-title"><a href="{plink Default:post 'slug'=>$post->slug}">{$post->headline}</a></h2>
		<p class="entry-date">{$post->created->format('M j, Y')}</p>
		{snippet:commentsLink}
			<p class="comments-link"><a href="{plink Default:post 'slug'=>$post->slug}#comments">{=count($comments)}</a></p>
		{/snippet}

		<div class="entry-content">
			{!$post->text|texy}
		</div><!-- .entry-content -->

		<p class="tag-links">
			<span>tagy: </span>
			{foreach $post->tags as $tag}
				<a href="{plink Default:tag 'tag'=>$tag->name}">{$tag->name}</a>
				{if !$iterator->isLast()}|{/if}
			{/foreach}
		</p>
	</div><!-- .post -->





	<div id="comments">
		<h3>Comments</h3>

		{snippet:comments}
			<p class="comments-link">{=count($comments)}</p>

			{if !empty($comments)}

				<ol id="commentlist">
					{foreach $comments as $comment}
						<li id="comment-{$comment->id}">
							<div class="commentHead">
								<a class="commentPermalink" href="#comment-{$comment->id}">#{$iterator->getCounter()}</a>
								<div class="commentAuthor">
									{if $comment->authorUrl}
										<a href="http://{$comment->authorUrl}">{$comment->author}</a>
									{else}
										{$comment->author}
									{/if}
								</div>
								<p class="commentDate">{$comment->created->format('M j, Y, H:i')}</p>
							</div>

							<div class="commentBody">
								{!$comment->text|texy}
							</div>
						</li><!-- comment -->
					{/foreach}
				</ol><!-- #commentlist -->

			{else}

				<p>No comments yet</p>

			{/if}
		{/snippet}


		{snippet:commentForm}
			{control commentForm begin}

				{var form => $control['commentForm']}

				{if !$form->hasErrors()}
					<h3>Leave a Reply</h3>
				{else}
					<h3 class="error">Form contains errors</h3>
				{/if}

				<span class="error bottom" n:foreach="$form[Nette\Forms\Form::PROTECTOR_ID]->errors as $error">{$error}</span>

				{*if is_user_logged_in()*}

						<!--
						<p>Logged in as <a href="profile.php">{*$user_identity*}</a>.
						<a href="logout" title="Log out of this account">Log out &raquo;</a></p>
						-->

				{*else*}

					<p>
						{$form['author']->control}
						{$form['author']->label}
						<span class="error" n:foreach="$form['author']->errors as $error">{$error}</span>
					</p>

					<p>
						{$form['authorEmail']->control}
						{$form['authorEmail']->label}
						<span class="error" n:foreach="$form['authorEmail']->errors as $error">{$error}</span>
					</p>

					<p>
						{$form['authorUrl']->control}
						{$form['authorUrl']->label}
						<span class="error" n:foreach="$form['authorUrl']->errors as $error">{$error}</span>
					</p>

				{*/if*}

				<p>
					{$form['comment']->control}
					{$form['comment']->label}
					<span class="error" n:foreach="$form['comment']->errors as $error">{$error}</span>
				</p>

				<p>{$form['send']->control}</p>

			{control commentForm end}
		{/snippet}

	</div><!-- #comments -->

</div><!-- #posts -->
