{block #content}

<h2 class="section">Tag &bdquo;{$tagName}&ldquo;</h2>

<div id="posts">
	{foreach $posts as $post}

		<div class="post">
			<h3 class="entry-title"><a href="{plink Default:post 'slug'=>$post->getSlug()}">{$post->getHeadline()}</a></h3>
			<p class="entry-date">{$post->getCreated()->format('M j, Y')}</p>
			<p class="comments-link"><a href="{plink Default:post 'slug'=>$post->getSlug()}#comments">{=count($post->getComments())}</a></p>

			<div class="entry-content">
				{!$post->getText()}
			</div><!-- .entry-content -->
		</div><!-- .post -->

	{/foreach}
</div><!-- #posts -->
