<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{block #title}NBlog administration{/block}</title>

	<meta name="description" content="">

	<link rel="shortcut icon" href="{$basePath}/favicon.ico">
	<link rel="stylesheet" href="{$basePath}/css/admin/main.css?v=1" media="screen">
	{block #styles}{/block}
</head>
<body>
<div id="wrapper">

	<header>
		<h1><a href="{$baseUri}">NBlog<span></span></a></h1>

		<p id="userbox">
			loggedin <strong>{$user->getIdentity()->name}</strong> [{? echo implode(', ', $user->roles)}] |
			<a href="{link Dashboard:logout}">odhlásiť</a>
		</p><!-- #userbox -->
	</header>



	<div id="main">
		{include #content}
	</div><!-- #main -->



	<footer>
		<p>Copyright &copy; Srigi, 2010</p>
	</footer>

</div><!-- #wrapper -->

{snippet:flashes}
	{if !empty($flashes)}
		<div id="flashes">
			{foreach $flashes as $flash}
				<div class="flash {$flash->type}">{$flash->message}</div>
			{/foreach}
		</div>
	{/if}
{/snippet}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script>!window.jQuery && document.write('<script src="{$basePath}/js/jquery-1.4.2.min.js"><\/script>')</script>
<script src="{$basePath}/js/funcs.js"></script>
{block #javascripts}{/block}
</body>
</html>
