<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{block #title}NBlog administration{/block}</title>

	<meta name="description" content="">

	<link rel="shortcut icon" href="{$basePath}/favicon.ico">
	<link rel="stylesheet" href="{$basePath}/css/admin/main.css?v=1" media="screen">
	{block #styles}{/block}
</head>
<body>
<div id="whole">
<div id="wrapper">

	<header>
		<h1><a href="{plink Dashboard:}">NBlog<span></span></a></h1>

		<p id="userbox">
			logged in <a href="{plink Settings:#user}">{$user->identity->name}</a> [{? echo implode(', ', $user->roles)}]
			<a id="logout" href="{link Dashboard:logout}" title="logout">logout</a>
		</p><!-- #userbox -->
	</header>



	<div id="main">
		<div id="sidebar">
		<div id="sidebarInner">
			<nav>
				<a href="{plink Posts:}">Posts</a>
				<a href="{plink Comments:}">Comments</a>
				<a href="{plink Media:}">Media</a>
				<hr>
				<a href="{plink Settings:}">Settings</a>
			</nav>
		</div><!-- #sidebarInner -->
		</div><!-- #sidebar -->

		<div id="content">
		<div id="contentInner">
			{include #content}
		</div><!-- #contentInner -->
		</div><!-- #content -->
		<div class="clearfix"></div>
	</div><!-- #main -->



	<footer>
		<p>Copyright &copy; Srigi, 2010</p>
	</footer>

</div><!-- #wrapper -->
</div><!-- #whole -->

{snippet:flashes}
	{if !empty($flashes)}
		<div id="flashes">
			{foreach $flashes as $flash}
				<div class="flash {$flash->type}">{$flash->message}</div>
			{/foreach}
		</div>
	{/if}
{/snippet}

<script src="{$basePath}/js/jquery-1.4.2.min.js"></script>
<script src="{$basePath}/js/funcs.js"></script>
{block #javascripts}{/block}
</body>
</html>
