{block #content}

<div class="dashboardBox">
Fry, you can't just sit here in the dark listening to classical music. You seem malnourished. Are you suffering from intestinal parasites? I don't 'need' to drink. I can quit anytime I want! Meh. Is that a cooking show? I haven't felt much of anything since my guinea pig died.
OK, if everyone's finished being stupid. And I'd do it again! And perhaps a third time! But that would be it. That's a popular name today. Little "e", big "B"? It doesn't look so shiny to me. I had more, but you go ahead. Ah, yes! John Quincy Adding Machine. He struck a chord with the voters when he pledged not to go on a killing spree.
</div>

<div class="dashboardBox">
Bender, I didn't know you liked cooking. That's so cute. I meant 'physically'. Look, perhaps you could let me work for a little food? I could clean the floors or paint a fence, or service you sexually? And I'm his friend Jesus. Bender! Ship! Stop bickering or I'm going to come back there and change your opinions manually! Hello Morbo, how's the family?
Well, let's just dump it in the sewer and say we delivered it. Shinier than yours, meatbag. Morbo will now introduce tonight's candidates... PUNY HUMAN NUMBER ONE, PUNY HUMAN NUMBER TWO, and Morbo's good friend, Richard Nixon.
</div>

<div class="dashboardBox full">
Nulla facilisi. Donec vel velit erat. Mauris euismod commodo dolor, non tristique leo blandit at. Morbi ut mi nisl. Sed vel libero et lectus egestas adipiscing a id felis. Aliquam lobortis faucibus ligula, ac vehicula mauris sodales non. Nullam sagittis quam at tortor iaculis ac tincidunt arcu fringilla. Morbi sed risus nisl, id tincidunt neque. In erat lectus, aliquam ac vulputate et, sodales sit amet nibh. Sed consequat bibendum ultricies. Donec condimentum velit nisl, a semper felis. Etiam at diam ipsum. Duis molestie aliquet sapien, nec rutrum tellus cursus eget. Curabitur porttitor metus.
</div>