{block #content}

<h3>Dashboard</h3>

<div class="dashboardBox">
	<h4>statistics</h4>
	<table id="dashStats">
		<tr>
			<th>Posts</th>
			<td>{$statistics['posts']['numAll']}</td>
			<td class="notPublicNum">
				{if $statistics['posts']['numDrafts']}
					<span><strong>{$statistics['posts']['numDrafts']}</strong> drafts</span>
				{else}
					&nbsp;
				{/if}
			</td>
		</tr>

		<tr>
			<th>Comments</th>
			<td>{$statistics['comments']['numAll']}</td>
			<td class="notPublicNum">
				{if $statistics['comments']['numNotApproved']}
					<span><strong>{$statistics['comments']['numNotApproved']}</strong> pending</span>
				{else}
					&nbsp;
				{/if}
			</td>
		</tr>
	</table>
</div>

<div class="dashboardBox">
	<h4>recent comments</h4>
</div>

<div class="dashboardBox full">
	<h4>quick post</h4>

	{control quickPostForm begin}
		{var form => $control['quickPostForm']}
		<table id="quickpost">
			{if $form->hasErrors()}
				<tr>
					<td colspan="3">{control quickPostForm errors}</td>
				</tr>
			{/if}

			<tr>
				<th>{$form['headline']->label}</th>
				<td colspan="2">{$form['headline']->control}</td>
			</tr>

			<tr>
				<th>{$form['text']->label}</th>
				<td colspan="2">{$form['text']->control}</td>
			</tr>

			<tr>
				<th>{$form['tags']->label}</th>
				<td>{$form['tags']->control}</td>
				<td class="submit">{$form['draft']->control}{$form['publish']->control}</td>
			</tr>
		</table>
	{control quickPostForm end}
</div>
